# Generated by Django 5.1.4 on 2025-04-26 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bd_models", "0006_player_extra_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ball",
            options={
                "managed": True,
                "verbose_name": "countryball",
                "verbose_name_plural": "countryballs",
            },
        ),
        migrations.AlterModelOptions(
            name="ballinstance",
            options={"managed": True, "verbose_name": "countryball instance"},
        ),
        migrations.AlterField(
            model_name="ball",
            name="country",
            field=models.CharField(max_length=48, unique=True, verbose_name="Name"),
        ),
        migrations.CreateModel(
            name="Battle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "player1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battles",
                        to="bd_models.player",
                    ),
                ),
                (
                    "player2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battles2",
                        to="bd_models.player",
                    ),
                ),
            ],
            options={
                "db_table": "battle",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="BattleObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "ballinstance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battleobjects",
                        to="bd_models.ballinstance",
                    ),
                ),
                (
                    "battle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battleobjects",
                        to="bd_models.battle",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battleobjects",
                        to="bd_models.player",
                    ),
                ),
            ],
            options={
                "db_table": "battleobject",
                "managed": True,
            },
        ),
    ]
