# Generated by Django 5.1.4 on 2025-04-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bd_models", "0007_alter_ball_options_alter_ballinstance_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="accepted_tos",
            field=models.BooleanField(
                default=False, help_text="Whether you've accepted the TOS or not"
            ),
        ),
    ]
