# Generated by Django 5.1.4 on 2025-04-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bd_models", "0008_player_accepted_tos"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="trade_cooldown_policy",
            field=models.SmallIntegerField(
                choices=[(1, "Cooldown"), (2, "Bypass")],
                default=1,
                help_text="To bypass or not the trade cooldown",
            ),
        ),
    ]
