# Generated by Django 5.1.4 on 2025-05-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bd_models", "0009_player_trade_cooldown_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="coins",
            field=models.BigIntegerField(default=0, help_text="Amount of coins you have"),
        ),
    ]
