# Generated by Django 5.1.4 on 2025-05-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bd_models", "0010_player_coins"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="battles_today",
            field=models.IntegerField(default=0, help_text="Number of battles done today"),
        ),
        migrations.AddField(
            model_name="player",
            name="trades_today",
            field=models.IntegerField(default=0, help_text="Number of trades done today"),
        ),
    ]
