# Generated by Django 5.1.4 on 2025-05-06 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bd_models", "0011_player_battles_today_player_trades_today"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField(max_length=2000)),
                ("price", models.PositiveIntegerField(default=0, help_text="Price in coins")),
                ("rewards", models.TextField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Pack",
                "verbose_name_plural": "Packs",
                "db_table": "pack",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PackInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("opened", models.BooleanField(default=False)),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="bd_models.pack",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pack_instances",
                        to="bd_models.player",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pack Instance",
                "verbose_name_plural": "Pack Instances",
                "db_table": "packinstance",
                "managed": True,
            },
        ),
    ]
