# Generated by Django 5.1.4 on 2025-05-06 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bd_models", "0012_pack_packinstance"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="pack",
            table="packs",
        ),
    ]
