# Generated by Django 5.1.4 on 2025-05-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bd_models", "0013_alter_pack_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="pack",
            name="purchasable",
            field=models.BooleanField(
                default=True, help_text="Whether this pack can be purchased"
            ),
        ),
    ]
