# Generated by Django 5.1.4 on 2025-05-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bd_models", "0014_pack_purchasable"),
    ]

    operations = [
        migrations.AddField(
            model_name="ballinstance",
            name="packed",
            field=models.BooleanField(default=False),
        ),
    ]
