# Generated by Django 5.1.4 on 2025-05-09 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bd_models", "0015_ballinstance_packed"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Pack",
            new_name="Packs",
        ),
    ]
