# Generated by Django 5.1.4 on 2025-05-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bd_models", "0016_rename_pack_packs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packs",
            name="price",
            field=models.PositiveIntegerField(default=0, help_text="Price in points"),
        ),
    ]
