# Generated by Django 5.1.4 on 2025-05-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bd_models", "0017_alter_packs_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="ball",
            name="season",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(1, "F12024"), (2, "Champs"), (3, "F12025")],
                default=None,
                help_text="What season the ball is from",
                null=True,
            ),
        ),
    ]
