# Generated by Django 5.1.4 on 2025-05-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bd_models", "0020_alter_packs_rewards"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ball",
            name="season",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(1, "F1 2024"), (2, "Champions"), (3, "F1 2025"), (4, "Limited")],
                default=None,
                help_text="What season the ball is from",
                null=True,
            ),
        ),
    ]
