# Generated by Django 5.1.4 on 2025-05-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bd_models", "0021_alter_ball_season"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ball",
            options={"managed": True, "verbose_name": "car", "verbose_name_plural": "cars"},
        ),
        migrations.AlterModelOptions(
            name="ballinstance",
            options={"managed": True, "verbose_name": "car instance"},
        ),
        migrations.AddField(
            model_name="ball",
            name="overlay",
            field=models.CharField(
                blank=True, help_text="Image used as a card overlay", max_length=200, null=True
            ),
        ),
    ]
