# Generated by Django 5.1.4 on 2025-05-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bd_models", "0022_alter_ball_options_alter_ballinstance_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ball",
            name="overlay",
            field=models.ImageField(
                blank=True,
                help_text="Image used as a card overlay",
                max_length=200,
                null=True,
                upload_to="",
            ),
        ),
    ]
