# Generated by Django 5.1.4 on 2025-05-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bd_models", "0023_alter_ball_overlay"),
    ]

    operations = [
        migrations.AlterField(
            model_name="special",
            name="background",
            field=models.ImageField(
                blank=True,
                help_text="Image used as overlay",
                max_length=200,
                null=True,
                upload_to="",
            ),
        ),
    ]
