# Generated by Django 5.1.4 on 2025-05-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bd_models", "0024_alter_special_background"),
    ]

    operations = [
        migrations.AddField(
            model_name="special",
            name="overlay",
            field=models.ImageField(
                blank=True,
                help_text="Image used as overlay",
                max_length=200,
                null=True,
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="special",
            name="background",
            field=models.ImageField(
                blank=True,
                help_text="1428x2000 PNG image",
                max_length=200,
                null=True,
                upload_to="",
            ),
        ),
    ]
