# Generated by Django 5.1.4 on 2025-05-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bd_models", "0025_special_overlay_alter_special_background"),
    ]

    operations = [
        migrations.AddField(
            model_name="ballinstance",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
